"""
Report Generator
Converts structured agent output into a polished Markdown investment memo.
"""
from datetime import datetime


class ReportGenerator:
    def generate(self, startup_name: str, agent_results: dict, committee: dict) -> str:
        score = committee.get("overall_score", "N/A")
        verdict = committee.get("verdict", "N/A")
        conviction = committee.get("conviction_level", "N/A")
        now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

        lines = [
            f"# Investment Due Diligence Report: {startup_name}",
            f"> Generated: {now}  |  Score: **{score}/10**  |  Verdict: **{verdict}**  |  Conviction: **{conviction}**",
            "",
            "---",
            "",
            "## 📋 Executive Summary",
            "",
            committee.get("summary", "_No summary available._"),
            "",
            "---",
            "",
            "## 🏦 Investment Thesis",
            "",
            "**Bull Case:**", committee.get("bull_case", ""),
            "",
            "**Bear Case:**", committee.get("bear_case", ""),
            "",
            "**Investment Thesis:**", committee.get("investment_thesis", ""),
            "",
            "---",
            "",
            "## 📊 Score Breakdown",
            "",
            "| Dimension | Score |",
            "|-----------|-------|",
        ]

        breakdown = committee.get("score_breakdown", {})
        for k, v in breakdown.items():
            lines.append(f"| {k.title()} | {v}/10 |")

        lines += [
            f"| **OVERALL** | **{score}/10** |",
            "",
            "---",
            "",
        ]

        # Agent sections
        section_map = {
            "market": ("📈 Market Analysis", "overall_market_score"),
            "team": ("👥 Team Analysis", "overall_team_score"),
            "product": ("🚀 Product Analysis", "overall_product_score"),
            "financials": ("💰 Financial Analysis", "overall_financial_score"),
            "competitive": ("🔍 Competitive Intelligence", "overall_competitive_score"),
            "risk": ("⚠️ Risk Assessment", "overall_risk_score"),
        }

        for key, (title, score_key) in section_map.items():
            r = agent_results.get(key, {})
            if not r:
                continue
            lines += [
                f"## {title}",
                f"**Score:** {r.get(score_key, 'N/A')}/10",
                "",
                r.get("summary", "_No summary._"),
                "",
            ]

        lines += [
            "---",
            "",
            "## ❓ Key Diligence Questions",
            "",
        ]
        for q in committee.get("key_diligence_questions", []):
            lines.append(f"- {q}")

        lines += [
            "",
            "## 🔜 Recommended Next Steps",
            "",
        ]
        for s in committee.get("next_steps", []):
            lines.append(f"1. {s}")

        lines += [
            "",
            "---",
            f"*This report was generated by AI VC Due Diligence Agent Team. Always validate findings with primary research.*",
        ]

        return "\n".join(lines)
